name: Deploy Azure VM
on: [push]

permissions:
  id-token: write
  # contents: read

env:
   AZURE_RESOURCE_GROUP: automation-lab

jobs:
  deploy-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Azure VM
        run: |
           az vm create \
           --resource-group ${{env.AZURE_RESOURCE_GROUP}} \
           --name ubuntu \
           --image Ubuntu2204 \
           --admin-username azureuser \
           --generate-ssh-keys
